# Generated by Django 4.1.6 on 2023-06-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_album_chef_musisi_resep_delete_item_album_artis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
