# Generated by Django 4.1.6 on 2023-06-16 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_kewarganegaraan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='kewarganegaraan',
            name='artis',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nat_artis', to='base.musisi'),
        ),
    ]
