# Generated by Django 4.1.6 on 2023-06-16 16:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_lokasi_alter_kewarganegaraan_artis'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokasi',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
