# Generated by Django 4.1.6 on 2023-06-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_lokasi_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasi',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lokasi',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
