# Generated by Django 4.1.6 on 2023-06-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_lokasi_lat_alter_lokasi_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasi',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lokasi',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
