# Generated by Django 4.2.2 on 2023-06-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_lokasi_lat_alter_lokasi_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokasi',
            name='gmaps_url',
            field=models.URLField(null=True),
        ),
    ]
