# Generated by Django 4.2.2 on 2023-06-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_lokasi_gmaps_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
                ('dokumen', models.FileField(null=True, upload_to='assets', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Gambar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='assets', verbose_name='')),
                ('galeri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gambar', to='base.galeri')),
            ],
        ),
    ]
