# Generated by Django 4.2.2 on 2023-06-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_galeri_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeri',
            name='dok_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gambar',
            name='foto_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
