# Generated by Django 4.2.2 on 2023-06-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_galeri_dok_url_gambar_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeri',
            name='tahun',
            field=models.IntegerField(null=True),
        ),
    ]
