# Generated by Django 4.2.2 on 2023-06-30 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_galeri_tahun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lokasi',
            name='gmaps_url',
        ),
    ]
