# Generated by Django 4.2.2 on 2023-07-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_galeri_dok_url_remove_gambar_foto_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(null=True, upload_to='assets', verbose_name='')),
                ('galeri', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='berkas', to='base.galeri')),
            ],
        ),
    ]
