# Generated by Django 4.2.2 on 2023-07-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_berkas'),
    ]

    operations = [
        migrations.AddField(
            model_name='berkas',
            name='ket',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gambar',
            name='ket',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
