# Generated by Django 4.2.2 on 2023-07-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('telepon', models.CharField(max_length=13)),
                ('foto_profil', models.ImageField(upload_to='assets', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
