# Generated by Django 4.2.2 on 2023-07-07 16:07

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_detail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkas',
            name='pdf',
            field=models.FileField(null=True, upload_to='assets', validators=[base.models.PDFValidator()], verbose_name=''),
        ),
    ]
