# Generated by Django 4.2.2 on 2023-07-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_berkas_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokasi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
