# Generated by Django 4.2.2 on 2023-07-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_lokasi_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokasi',
            name='month_year',
            field=models.DateField(null=True),
        ),
    ]
