# Generated by Django 4.2.2 on 2023-07-10 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_lokasi_month_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koperasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PermintaanProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(max_length=10)),
                ('permintaan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
                ('omzet', models.IntegerField()),
                ('skala', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JenisProdukUMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komoditi', models.CharField(max_length=10)),
                ('umkm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jenis_produk_umkm', to='base.umkm')),
            ],
        ),
        migrations.CreateModel(
            name='JenisProdukKoperasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komoditi', models.CharField(max_length=10)),
                ('koperasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jenis_produk_koperasi', to='base.koperasi')),
            ],
        ),
    ]
