# Generated by Django 4.2.2 on 2023-07-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_permintaanproduk_umkm'),
    ]

    operations = [
        migrations.AddField(
            model_name='permintaanproduk',
            name='produksi',
            field=models.IntegerField(null=True),
        ),
    ]
